// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR API KEY',
    appId: 'YOUR APP ID',
    messagingSenderId: 'YOUR MESSAGING SENDER ID',
    projectId: 'YOUR PROJECT ID',
    authDomain: 'YOUR AUTH DOMAIN',
    storageBucket: 'YOUR STORAGE BUCKET',
    measurementId: 'YOUR MEASUREMENT ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR API KEY',
    appId: 'YOUR APP ID',
    messagingSenderId: 'YOUR MESSAGING SENDER ID',
    projectId: 'YOUR PROJECT ID',
    storageBucket: 'YOUR STORAGE BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR API KEY',
    appId: 'YOUR APP ID',
    messagingSenderId: 'YOUR MESSAGING SENDER ID',
    projectId: 'YOUR PROJECT ID',
    storageBucket: 'YOUR STORAGE BUCKET',
    iosClientId: 'YOUR IOS CLIENT ID',
    iosBundleId: 'YOUR IOS BUNDLE ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR API KEY',
    appId: 'YOUR APP ID',
    messagingSenderId: 'YOUR MESSAGING SENDER ID',
    projectId: 'YOUR PROJECT ID',
    storageBucket: 'YOUR STORAGE BUCKET',
    iosClientId: 'YOUR IOS CLIENT ID',
    iosBundleId: 'YOUR IOS BUNDLE ID',
  );
}
