// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyBElqNMqzBG7hIrDctt81R8MQEimxnUw54',
      appId: '1:844729573669:web:49f9e2291851489892bacc',
      messagingSenderId: '844729573669',
      projectId: 'netflixclone-4510d',
      authDomain: 'netflixclone-4510d.firebaseapp.com',
      storageBucket: 'netflixclone-4510d.appspot.com',
      measurementId: 'G-QH3R4BEK3V');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAer5u1e-J_QXRtg26JQrZkpIR2sI3f5Y',
    appId: '1:844729573669:android:a53cd83e8fb983de92bacc',
    messagingSenderId: '844729573669',
    projectId: 'netflixclone-4510d',
    storageBucket: 'netflixclone-4510d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5tLS902QDypdT3CqdKjlz-xFTwPXz9nY',
    appId: '1:844729573669:ios:2c5d7f7993c3b1b192bacc',
    messagingSenderId: '844729573669',
    projectId: 'netflixclone-4510d',
    storageBucket: 'netflixclone-4510d.appspot.com',
    iosClientId: '844729573669-m67jfhoehgia0bdn4rj0qbfqumer2r31.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5tLS902QDypdT3CqdKjlz-xFTwPXz9nY',
    appId: '1:844729573669:ios:0063c1467912d6bc92bacc',
    messagingSenderId: '844729573669',
    projectId: 'netflixclone-4510d',
    storageBucket: 'netflixclone-4510d.appspot.com',
    iosClientId: '844729573669-ud7efh7slef1j235eg8sg0f24s332b77.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixClone.RunnerTests',
  );
}
